site_name: Friends with Kubernetes
site_url: https://elastisys.github.io/tutorial-friends-with-kubernetes/
site_description: Learn how to avoid common pitfalls when porting your application to Kubernetes.
site_author: Cristian Klein
copyright: Copyright © 2020 Cristian Klein

repo_url: https://github.com/elastisys/tutorial-friends-with-kubernetes

google_analytics:
  - UA-36723568-3
  - auto

theme:
  name: material
  custom_dir: overrides

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Home: 'index.md'
  - 'State Creep': 'state-creep.md'
