site_name: Friends with Kubernetes
site_url: https://elastisys.github.io/tutorial-friends-with-kubernetes/
site_description: Learn how to avoid common pitfalls when porting your application to Kubernetes.
site_author: Cristian Klein
copyright: Copyright © 2020 Cristian Klein

theme:
  name: material
  custom_dir: overrides

markdown_extensions:
  - admonition

nav:
  - Home: 'index.md'
  - 'State Creep': 'state-creep.md'
