apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: srp-server
  name: srp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srp-server
  template:
    metadata:
      labels:
        app: srp-server
    spec:
      containers:
      - image: srp-server-redis:latest
        imagePullPolicy: Never
        name: srp-server
        env:
          - name: REDIS_MASTER
            value: "redis-master:6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: "redis-password"
